---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: enablePerkPreview

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: membershipTier
          operator: in-array
          operands:
            - basic
    flagValue: true
