---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: enableEarlyAccess

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: membershipTier
          operator: in-array
          operands:
            - vip
            - beta
    flagValue: true
