---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-properties

name: isPremiumCustomer
type: Boolean
description: "Indicates if the customer is a premium/VIP member with elevated benefits"
