---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: cartCountdownTimer
flagType: number
description: Gear reservation timer to reduce cart abandonment. Create urgency for popular/limited outdoor gear. Test optimal timer duration for conversion. Personalize pressure based on customer tier.
labels:

availableValues:

isPermanent: false
