---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: ecommerce.productDisplayMode
flagType: string
description: ""
labels:

availableValues:
  - grid
  - list
  - compact

isPermanent: false
