---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: enableBlackFriday
flagType: boolean
description: Enable site-wide Black Friday deals - 20% off all items + free shipping (no minimum). Launch instantly without code deploy. Enable 1 week early for VIP/Summit members. Disable instantly if inventory runs low.
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
