---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: enableRecommendations
flagType: boolean
description: Show "Complete Your Kit" personalized gear suggestions. Increase average order value by suggesting complementary gear. A/B test recommendation algorithm effectiveness. Gradually roll out to measure performance impact.
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
