---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: enableExpressCheckout
flagType: boolean
description: One-click express checkout for Pro members and returning outdoor enthusiasts. Reduce friction for high-value customers. Test impact on conversion rate and cart abandonment. Reward loyalty with premium checkout experience.
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
