---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: enableEarlyAccess
flagType: boolean
description: Exclusive new arrivals for Summit (VIP) members. Summit sees exclusive products, others see upgrade teaser. Reward top-tier customers with first access to new gear. Drive upgrades to Summit membership. Create exclusivity and urgency around new drops.
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
