---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: freeShippingThreshold
flagType: number
description: Minimum order value for free standard shipping on outdoor orders. Increase average order value. Test different thresholds for revenue optimization. Incentivize new customers with lower threshold.
labels:

availableValues:

isPermanent: false
