---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: productsPerPage
flagType: number
description: Control pagination size for gear listings. Test optimal page size for browsing outdoor gear. Balance performance vs. content visibility. Personalize based on customer tier or device
labels:

availableValues:

isPermanent: false
