---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: productDisplayMode
flagType: string
description: A/B test different gear layout styles. Test which layout drives more engagement and add-to-carts. Optimize for different device types (mobile vs desktop). Personalize based on user shopping preference.
labels:

availableValues:

isPermanent: false
