---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: promoBannerTheme
flagType: string
description: A/B test different banner themes for outdoor campaigns. Test which nature-inspired theme gets more clicks. Optimize promotional banner effectiveness. Match seasonal outdoor themes.
labels:

availableValues:

isPermanent: false
