---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: showPromoBanner
flagType: boolean
description: Toggle seasonal outdoor campaign banner (end-of-season sale, Worn Wear events). Launch seasonal clearance instantly without code deploy. Test impact of outdoor campaign messaging on conversion. Target campaigns to specific regions or customer segments.
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
