---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: testBanner
flagType: boolean
description: Demo a bad deploy - banner with clashing colors, broken layout, overlapping text. Perfect for showing instant rollback via feature flags. Used for demonstrating risk mitigation and instant rollback capabilities.
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
